name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java (change 17 → your version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Compile Java
      - name: Compile Java code
        run: javac $(find . -name "*.java")

      # Run tests (optional, if you have Main class or JUnit)
      - name: Run Java Program
        run: java com.example.assignment.Main
        if: success()

